###
# All persons
GET http://localhost:3001/api/persons


###
GET http://localhost:3001/info

###
# One person
GET http://localhost:3001/api/persons/1

###
# Person that doesn't exist 
GET http://localhost:3001/api/persons/99


###
# remove person
DELETE http://localhost:3001/api/persons/1

####
# Add person
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "bert",
    "number": "123"
}

####
# Add person with name that already exists
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "789"
}


####
# Number is missing
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Kurt"
}

####
# Name is missing
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "456"
}